Enhance branch name validation workflow to support both push and pull request events

diff --git a/.github/workflows/branch_name_validation_action.yml b/.github/workflows/branch_name_validation_action.yml
--- a/.github/workflows/branch_name_validation_action.yml
+++ b/.github/workflows/branch_name_validation_action.yml
@@ -10,9 +10,10 @@ on:
       - development  # Trigger on pull request to development branch
 
 jobs:
-  Validate_Feature_Branch:
-    name: Validate Branch
+  Validate_Feature_Branch_On_Push:
+    name: Validate Branch on Push
     runs-on: ubuntu-latest
+    if: github.event_name == 'push'
 
     steps:
       - uses: actions/checkout@v3
@@ -21,6 +22,32 @@ jobs:
         run: |
           # Extract the current branch name
           BRANCH_NAME=${GITHUB_REF_NAME}
+
+          # Define the regex pattern
+          PATTERN="^(feat|bugfix|hotfix|release)\/FECOM-[0-9]+-[A-Za-z0-9-]+$"
+
+          echo "Validating branch name '$BRANCH_NAME'..."
+
+          # Check if the branch name matches the pattern
+          if [[ ! "$BRANCH_NAME" =~ $PATTERN ]]; then
+            echo "Error: Branch name '$BRANCH_NAME' does not match the required pattern."
+            exit 1
+          else
+            echo "Branch name '$BRANCH_NAME' is valid."
+          fi
+
+  Validate_Feature_Branch_On_PR:
+    name: Validate Branch on Pull Request
+    runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request'
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Validate Branch Name
+        run: |
+          # Extract the current branch name
+          BRANCH_NAME=${GITHUB_HEAD_REF}
 
           # Define the regex pattern
           PATTERN="^(feat|bugfix|hotfix|release)\/FECOM-[0-9]+-[A-Za-z0-9-]+$"
